{
  "test_status": "failed",
  "test_failure": {
    "message": "AssertionError: False is not true",
    "location": "simple/test_simple.py:27"
  },
  "exception": {
    "class": "AssertionError",
    "message": "False is not true"
  }
}
